spring:
  application:
    name: demo

  data:
    mongodb:
      uri: mongodb+srv://${DATABASE_USER}:${DATABASE_PASSWORD}@cluster0.ly4vv.mongodb.net/${DATABASE_NAME}?retryWrites=true&w=majority

webclient:
  music: ${MUSICBRAINZ_API_URL}
  thumbnail: ${COVER_ART_ARCHIVE_API_URL}
  movie: ${TMDB_API_URL}
  series: ${TMDB_API_URL}
  tmdb-token: ${TMDB_ACCESS_TOKEN}
  tmdb-poster-url: ${TMDB_POSTER_URL}
  book: ${KAKAO_API_URL}
  kakao-api-key: ${KAKAO_API_KEY}